#!/bin/bash

if [ ! -f "/var/lib/webosbrew/init.d/homescreen_cleaner" ]; then
	curl -s -L https://github.com/nnmdd/homescreen_cleaner/raw/main/homescreen_cleaner > /var/lib/webosbrew/init.d/homescreen_cleaner
	chmod +x /var/lib/webosbrew/init.d/homescreen_cleaner
	/var/lib/webosbrew/init.d/homescreen_cleaner && exit 0
fi


mkdir -p /tmp/homescreen_cleaner
echo "return" > /tmp/homescreen_cleaner/TopShelf.qml
echo "return" > /tmp/homescreen_cleaner/RecentBG.qml
echo "return" > /tmp/homescreen_cleaner/AppInterfaces.qml
echo "return" > /tmp/homescreen_cleaner/Recommended.qml
echo "return" > /tmp/homescreen_cleaner/CPShelf.qml
echo "return" > /tmp/homescreen_cleaner/AIBoard.qml
echo "return" > /tmp/homescreen_cleaner/AdShelf.qml

mount --bind /tmp/homescreen_cleaner/TopShelf.qml /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/TopShelf.qml
mount --bind /tmp/homescreen_cleaner/RecentBG.qml /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/RecentBG.qml
mount --bind /tmp/homescreen_cleaner/AppInterfaces.qml /usr/palm/applications/com.webos.app.home/qml/Interfaces/AppInterfaces/AppInterfaces.qml
mount --bind /tmp/homescreen_cleaner/Recommended.qml /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/Recommended.qml
mount --bind /tmp/homescreen_cleaner/CPShelf.qml /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/CPShelf.qml
mount --bind /tmp/homescreen_cleaner/AIBoard.qml /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/AIBoard.qml
mount --bind /tmp/homescreen_cleaner/AdShelf.qml /usr/palm/applications/com.webos.app.home/qml/UserInterfaceLayer/Containers/Main/AdShelf.qml

pkill -f com.webos.app.home
